-- 목적: 기존 1:1 문의를 문의·요청 워크플로(유형·상태·대화·알림)로 재구성한다.
-- 적용 대상: PostgreSQL 15 / 기존 TPMP 데이터베이스
-- 정책: 모든 DDL·시드는 재실행 가능하며 기존 답변은 SYSTEM 메시지로 보존한다.

BEGIN;

-- 1. 문의 컬럼을 확장하고 기존 유형을 새 접수 목적·발생 영역으로 이관한다.
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS request_type VARCHAR(50);
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS target_area VARCHAR(100);
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS detail_location VARCHAR(500);

ALTER TABLE inquiries DROP CONSTRAINT IF EXISTS inquiries_status_check;
ALTER TABLE inquiries DROP CONSTRAINT IF EXISTS inquiries_inquiry_type_check;
ALTER TABLE inquiries DROP CONSTRAINT IF EXISTS inquiries_request_type_check;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'inquiries' AND column_name = 'inquiry_type'
    ) THEN
        UPDATE inquiries
        SET request_type = CASE inquiry_type
            WHEN 'BUG' THEN 'BUG_REPORT'
            WHEN 'EXAM' THEN 'GENERAL_INQUIRY'
            WHEN 'CONCEPT_NOTE' THEN 'GENERAL_INQUIRY'
            WHEN 'DAILY_QUIZ' THEN 'GENERAL_INQUIRY'
            WHEN 'PRACTICE' THEN 'GENERAL_INQUIRY'
            ELSE 'OTHER'
        END
        WHERE request_type IS NULL;

        UPDATE inquiries
        SET target_area = CASE inquiry_type
            WHEN 'BUG' THEN 'OTHER'
            WHEN 'EXAM' THEN 'EXAM_INFO'
            WHEN 'CONCEPT_NOTE' THEN 'CONCEPT_NOTE'
            WHEN 'DAILY_QUIZ' THEN 'DAILY_QUIZ'
            WHEN 'PRACTICE' THEN 'PRACTICE_SCRATCHPAD'
            ELSE target_area
        END
        WHERE target_area IS NULL;
    END IF;
END;
$$;

UPDATE inquiries SET request_type = 'OTHER' WHERE request_type IS NULL;
UPDATE inquiries
SET status = 'COMPLETED'
WHERE request_type = 'BUG_REPORT' AND status = 'ANSWERED';

-- 2. 기존 관리자 답변을 SYSTEM 작성자의 첫 대화 메시지로 보존한다.
CREATE TABLE IF NOT EXISTS inquiry_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id BIGINT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    author_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    author_role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inquiry_messages_author_role_check CHECK (author_role IN ('USER', 'ADMIN', 'SYSTEM'))
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'inquiries' AND column_name = 'reply'
    ) THEN
        EXECUTE $migration$
            INSERT INTO inquiry_messages (inquiry_id, author_id, author_role, content, created_at)
            SELECT i.id, NULL, 'SYSTEM', i.reply, COALESCE(i.replied_at, i.created_at, CURRENT_TIMESTAMP)
            FROM inquiries i
            WHERE i.reply IS NOT NULL AND BTRIM(i.reply) <> ''
              AND NOT EXISTS (
                  SELECT 1 FROM inquiry_messages message
                  WHERE message.inquiry_id = i.id
                    AND message.author_role = 'SYSTEM'
                    AND message.content = i.reply
              )
        $migration$;
    END IF;
END;
$$;

ALTER TABLE inquiries DROP COLUMN IF EXISTS reply;
ALTER TABLE inquiries DROP COLUMN IF EXISTS replied_at;
ALTER TABLE inquiries DROP COLUMN IF EXISTS inquiry_type;
ALTER TABLE inquiries ALTER COLUMN request_type SET NOT NULL;

ALTER TABLE inquiries ADD CONSTRAINT inquiries_request_type_check
    CHECK (request_type IN ('GENERAL_INQUIRY', 'BUG_REPORT', 'EXAM_OPENING_REQUEST', 'FEATURE_REQUEST', 'OTHER'));
ALTER TABLE inquiries ADD CONSTRAINT inquiries_status_check
    CHECK (status IN ('PENDING', 'IN_PROGRESS', 'ON_HOLD', 'ANSWERED', 'COMPLETED', 'UNABLE_TO_PROCESS'));

-- 3. 대화 첨부와 업로더 소유권을 추가한다.
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS uploaded_by BIGINT;
ALTER TABLE attachments DROP CONSTRAINT IF EXISTS attachments_ref_type_check;
ALTER TABLE attachments ADD CONSTRAINT attachments_ref_type_check
    CHECK (ref_type IN ('INQUIRY', 'INQUIRY_MESSAGE', 'QUESTION_BANK'));

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'attachments_uploaded_by_fkey'
          AND conrelid = 'public.attachments'::regclass
    ) THEN
        ALTER TABLE attachments
            ADD CONSTRAINT attachments_uploaded_by_fkey
            FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL;
    END IF;
END;
$$;

-- 4. 관리자 수신 설정과 비동기 메일 발송 이력을 위한 저장소를 만든다.
CREATE TABLE IF NOT EXISTS inquiry_notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 전역 설정은 항상 고정 PK 1행만 사용한다. 과거에 잘못 생성된 다중 행은 id=1로 정리한다.
INSERT INTO inquiry_notification_settings (id, enabled, updated_at)
SELECT 1,
       COALESCE((SELECT enabled FROM inquiry_notification_settings ORDER BY id ASC LIMIT 1), FALSE),
       CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM inquiry_notification_settings WHERE id = 1);

DELETE FROM inquiry_notification_settings WHERE id <> 1;

ALTER TABLE inquiry_notification_settings DROP CONSTRAINT IF EXISTS inquiry_notification_settings_singleton_id_check;
ALTER TABLE inquiry_notification_settings
    ADD CONSTRAINT inquiry_notification_settings_singleton_id_check CHECK (id = 1);

SELECT setval(pg_get_serial_sequence('inquiry_notification_settings', 'id'), 1, TRUE);

CREATE TABLE IF NOT EXISTS inquiry_notification_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settings_id BIGINT NOT NULL REFERENCES inquiry_notification_settings(id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inquiry_notification_recipients_settings_email_key UNIQUE (settings_id, email)
);

CREATE TABLE IF NOT EXISTS inquiry_email_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id BIGINT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    inquiry_message_id BIGINT NULL REFERENCES inquiry_messages(id) ON DELETE SET NULL,
    event_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    recipient_email VARCHAR(255) NOT NULL,
    subject VARCHAR(500) NOT NULL,
    body TEXT NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP NULL,
    CONSTRAINT inquiry_email_deliveries_event_type_check CHECK (
        event_type IN ('NEW_INQUIRY', 'USER_MESSAGE', 'ADMIN_MESSAGE', 'ANSWERED', 'COMPLETED', 'UNABLE_TO_PROCESS')
    ),
    CONSTRAINT inquiry_email_deliveries_status_check CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_inquiry_messages_inquiry_created_at
    ON inquiry_messages (inquiry_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_inquiry_email_deliveries_inquiry_id
    ON inquiry_email_deliveries (inquiry_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inquiry_email_deliveries_pending
    ON inquiry_email_deliveries (status) WHERE status IN ('PENDING', 'FAILED');

-- 5. 신규 작성 화면이 사용할 도메인 값을 멱등 시드한다.
INSERT INTO domain_master (code, name)
VALUES ('INQUIRY_CATEGORY', '문의 카테고리')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO domain_master (code, name)
VALUES ('INQUIRY_BUG_AREA', '문의 버그 발생 영역')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- inquiries는 유형 문자열만 저장하므로 구형 카테고리 슬레이브를 참조하지 않는다.
-- 삭제 전에 다른 업무 도메인이 잘못 참조했다면 FK 오류로 중단되어 무결성을 보존한다.
DELETE FROM domain_slave slave
USING domain_master master
WHERE slave.master_id = master.id
  AND master.code = 'INQUIRY_CATEGORY'
  AND slave.name IN ('EXAM', 'CONCEPT_NOTE', 'DAILY_QUIZ', 'PRACTICE', 'BUG');

WITH values_to_seed(name, display_order) AS (
    VALUES
        ('GENERAL_INQUIRY', 1), ('BUG_REPORT', 2), ('EXAM_OPENING_REQUEST', 3),
        ('FEATURE_REQUEST', 4), ('OTHER', 5)
)
INSERT INTO domain_slave (master_id, name, display_order)
SELECT master.id, value.name, value.display_order
FROM domain_master master
CROSS JOIN values_to_seed value
WHERE master.code = 'INQUIRY_CATEGORY'
  AND NOT EXISTS (
      SELECT 1 FROM domain_slave slave WHERE slave.master_id = master.id AND slave.name = value.name
  );

WITH values_to_seed(name, display_order) AS (
    VALUES
        ('LOGIN_ACCOUNT', 1), ('USER_HOME', 2), ('EXAM_INFO', 3), ('EXAM_SOLVING_RESULT', 4),
        ('DAILY_QUIZ', 5), ('CONCEPT_NOTE', 6), ('PRACTICE_SCRATCHPAD', 7),
        ('INQUIRY_REQUEST', 8), ('OTHER', 9)
)
INSERT INTO domain_slave (master_id, name, display_order)
SELECT master.id, value.name, value.display_order
FROM domain_master master
CROSS JOIN values_to_seed value
WHERE master.code = 'INQUIRY_BUG_AREA'
  AND NOT EXISTS (
      SELECT 1 FROM domain_slave slave WHERE slave.master_id = master.id AND slave.name = value.name
  );

UPDATE menu_config SET name = '문의·요청' WHERE url = '/user/inquiries';
UPDATE menu_config SET name = '문의·요청 관리' WHERE url = '/admin/inquiries';

COMMIT;

-- ROLLBACK은 이미 이관된 메시지·발송 이력의 유실 위험이 있어 운영 환경에서 제공하지 않는다.
