-- 목적: 릴리즈별 패치 항목과 활성 릴리즈 버전 유일성 지원
-- 적용 대상: PostgreSQL 15 / 기존 20260826_01_create_patch_notes.sql 적용 환경
-- 정책: 하위 항목과 릴리즈 모두 del_yn 논리 삭제를 사용하며, 활성 버전에만 유일 인덱스를 적용한다.
-- 롤백: 파일 하단의 ROLLBACK 절차를 별도 실행한다.

BEGIN;

CREATE TABLE IF NOT EXISTS patch_note_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patch_note_id BIGINT NOT NULL,
    item_type     VARCHAR(20) NOT NULL,
    summary       VARCHAR(200) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    create_dt     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_uno    BIGINT NOT NULL,
    modified_dt   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_uno  BIGINT NOT NULL,
    del_yn        VARCHAR(1) NOT NULL DEFAULT 'N',
    use_yn        VARCHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT ck_patch_note_items_type
        CHECK (item_type IN ('ADD', 'IMPROVEMENT', 'FIX', 'SECURITY', 'ETC')),
    CONSTRAINT ck_patch_note_items_display_order
        CHECK (display_order >= 0),
    CONSTRAINT fk_patch_note_items_patch_note
        FOREIGN KEY (patch_note_id) REFERENCES patch_notes (id)
);

CREATE INDEX IF NOT EXISTS idx_patch_note_items_patch_note_order
    ON patch_note_items (patch_note_id, del_yn, display_order ASC, id ASC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_patch_notes_version_active
    ON patch_notes (version)
    WHERE del_yn = 'N';

COMMENT ON TABLE patch_note_items IS '패치노트 릴리즈별 하위 변경 항목';
COMMENT ON COLUMN patch_note_items.item_type IS '항목 유형 (ADD/IMPROVEMENT/FIX/SECURITY/ETC)';
COMMENT ON COLUMN patch_note_items.summary IS '사용자에게 표시할 순수 텍스트 요약';
COMMENT ON COLUMN patch_note_items.display_order IS '릴리즈 내부 표시 순서 (0 이상)';

COMMIT;

-- ROLLBACK (필요 시 아래 문장을 별도 트랜잭션으로 실행)
-- BEGIN;
-- DROP INDEX IF EXISTS ux_patch_notes_version_active;
-- DROP TABLE IF EXISTS patch_note_items;
-- COMMIT;
