-- 목적: "개발자 응원하기(후원)" 페이지(/user/support)의 토스/카카오페이/카카오 선물하기 위시리스트
--       3개 외부 링크를 코드 상수가 아니라 관리자 화면(/admin/support-settings)에서 관리하기 위한
--       단일 행(싱글톤) 설정 테이블.
-- 적용 대상: PostgreSQL 15 / 신규 테이블 support_settings
-- 정책:
--   - 여러 행을 두지 않는 싱글톤 테이블 — 애플리케이션은 항상 id 오름차순 첫 번째 행을 조회/수정한다
--     (백엔드 SupportSettingsService.findOrCreate()가 없으면 자동 생성하는 방어 로직도 포함).
--   - 3개 URL 컬럼은 모두 nullable — 비어있으면 프론트엔드에서 해당 채널을 "준비 중" 비활성 카드로 렌더링.
-- 롤백: 파일 하단의 ROLLBACK 절차를 별도 실행한다.

BEGIN;

-- 적용 전 확인: 테이블 존재 여부
SELECT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = current_schema()
      AND table_name = 'support_settings'
) AS support_settings_table_exists;

CREATE TABLE IF NOT EXISTS support_settings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toss_url        VARCHAR(500) NULL,
    kakaopay_url    VARCHAR(500) NULL,
    kakao_gift_url  VARCHAR(500) NULL,
    updated_at      TIMESTAMP NULL
);

COMMENT ON TABLE support_settings IS '개발자 응원하기(후원) 링크 단일 행 설정 — 관리자 화면에서 관리';
COMMENT ON COLUMN support_settings.id IS 'PK';
COMMENT ON COLUMN support_settings.toss_url IS '토스 송금 링크, nullable(비어있으면 사용자 화면에서 준비 중으로 표시)';
COMMENT ON COLUMN support_settings.kakaopay_url IS '카카오페이 송금 링크, nullable';
COMMENT ON COLUMN support_settings.kakao_gift_url IS '카카오톡 선물하기 위시리스트 링크, nullable';
COMMENT ON COLUMN support_settings.updated_at IS '수정 일시, nullable';

-- 초기 싱글톤 행 1개 삽입(빈 값) — 이미 행이 있으면 건너뜀
INSERT INTO support_settings (toss_url, kakaopay_url, kakao_gift_url)
SELECT NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM support_settings);

-- 적용 후 검증: 컬럼 구조 및 싱글톤 행 확인
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = current_schema()
  AND table_name = 'support_settings'
ORDER BY ordinal_position;

SELECT id, toss_url, kakaopay_url, kakao_gift_url, updated_at FROM support_settings ORDER BY id;

COMMIT;

-- ROLLBACK (필요 시 아래 문장을 별도 트랜잭션으로 실행)
-- BEGIN;
-- DROP TABLE IF EXISTS support_settings;
-- COMMIT;
