-- 목적: "내 시험 접수 정보" 기능 — Q-net 공개 API는 종목별 공통 일정만 제공하고
--       개인별 접수 이력은 제공하지 않으므로, 사용자가 직접 입력한 접수일/시험일을 저장한다.
-- 적용 대상: PostgreSQL 15 / 신규 테이블 user_exam_applications
-- 정책:
--   - exam_info_id는 nullable FK (ON DELETE SET NULL) — exam_info가 삭제되어도 사용자 기록은 남긴다.
--   - exam_name은 저장 시점 스냅샷 — exam_info.title이 나중에 바뀌어도 접수 당시 이름을 유지한다.
--   - user_id는 FK (ON DELETE CASCADE) — 회원 탈퇴 시 함께 삭제한다.
--   - 재응시 등으로 동일 user_id + exam_info_id 조합이 여러 건 존재할 수 있어 유니크 제약을 두지 않는다.
-- 롤백: 파일 하단의 ROLLBACK 절차를 별도 실행한다.

BEGIN;

-- 적용 전 확인: 테이블 존재 여부
SELECT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = current_schema()
      AND table_name = 'user_exam_applications'
) AS user_exam_applications_table_exists;

CREATE TABLE IF NOT EXISTS user_exam_applications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    exam_info_id      BIGINT NULL,
    exam_name         VARCHAR(200) NOT NULL,
    application_date  DATE NULL,
    exam_date         DATE NULL,
    memo              VARCHAR(300) NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP NULL,
    CONSTRAINT fk_user_exam_applications_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_exam_applications_exam_info
        FOREIGN KEY (exam_info_id) REFERENCES exam_info(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_user_exam_applications_user_id
    ON user_exam_applications (user_id);

CREATE INDEX IF NOT EXISTS idx_user_exam_applications_exam_info_id
    ON user_exam_applications (exam_info_id);

COMMENT ON TABLE user_exam_applications IS '사용자가 직접 입력한 시험 접수(신청) 정보 — Q-net 공개 API가 제공하지 않는 개인별 접수 이력을 사용자가 수동으로 관리';
COMMENT ON COLUMN user_exam_applications.id IS 'PK';
COMMENT ON COLUMN user_exam_applications.user_id IS 'FK → users.id (접수 정보 소유자, ON DELETE CASCADE)';
COMMENT ON COLUMN user_exam_applications.exam_info_id IS 'FK → exam_info.id (연결된 시험 정보, nullable, ON DELETE SET NULL — 원본 삭제 시에도 기록은 유지)';
COMMENT ON COLUMN user_exam_applications.exam_name IS '시험명 스냅샷 (저장 시점 exam_info.title 또는 자유 입력값, exam_info.title이 이후 변경되어도 유지)';
COMMENT ON COLUMN user_exam_applications.application_date IS '접수일(신청일), nullable';
COMMENT ON COLUMN user_exam_applications.exam_date IS '시험일, nullable';
COMMENT ON COLUMN user_exam_applications.memo IS '사용자 메모, nullable';
COMMENT ON COLUMN user_exam_applications.created_at IS '생성 일시';
COMMENT ON COLUMN user_exam_applications.updated_at IS '수정 일시, nullable';

-- 적용 후 검증: 테이블·인덱스·FK 생성 확인
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = current_schema()
  AND table_name = 'user_exam_applications'
ORDER BY ordinal_position;

SELECT indexname
FROM pg_indexes
WHERE schemaname = current_schema()
  AND tablename = 'user_exam_applications';

SELECT conname, confrelid::regclass AS referenced_table, confdeltype
FROM pg_constraint
WHERE conrelid = 'user_exam_applications'::regclass
  AND contype = 'f';

COMMIT;

-- ROLLBACK (필요 시 아래 문장을 별도 트랜잭션으로 실행)
-- BEGIN;
-- DROP TABLE IF EXISTS user_exam_applications;
-- COMMIT;
