-- 목적: "2026년 1회 정보처리기사 실기 (AI 커스텀)" 시험을 신규 생성한다.
-- 배경: 기존 2026년 1회 기출 문항은 저작권 문제로 서비스 활용이 어려워, 동일 개념만
--       유지하고 코드 로직·문제 구성·값을 모두 새로 설계한 AI 커스텀 20문항으로 재구성한다.
--       (특히 CODE 문항은 원본 코드 골격을 재사용하지 않고 전혀 다른 코드로 같은 개념을 검증한다.)
--       정답은 CODE 유형 실행 결과를 직접 계산·검증했고, 단답은 기존 채점 규칙
--       (콤마/슬래시 다중값·열거 마커·괄호 대체표기·|| 대체정답)에 맞춰 작성했다.
-- 대상: exams(신규 1행) + questions(신규 20행, exam_id 연결). 기존 데이터는 손대지 않는다.
-- 재실행 안전: 동일 제목 시험이 있으면 재삽입하지 않고, 이미 문항이 있으면 재삽입하지 않는다.
-- id는 두 테이블 모두 GENERATED BY DEFAULT AS IDENTITY이므로 명시하지 않고 자동 생성한다.

BEGIN;

INSERT INTO exams (created_at, del_yn, order_no, question_mode, title, created_by)
SELECT now(), 'N', (SELECT COALESCE(MAX(order_no), 0) + 1 FROM exams), 'SEQUENTIAL',
       '2026년 1회 정보처리기사 실기 (AI 커스텀)', 1
WHERE NOT EXISTS (
    SELECT 1 FROM exams WHERE title = '2026년 1회 정보처리기사 실기 (AI 커스텀)' AND del_yn = 'N'
);

INSERT INTO questions (exam_id, seq, question_type, instruction, content, code, language, answer, explanation)
SELECT e.id, v.seq, v.qt, v.instr, v.content, v.code, v.lang, v.answer, v.expl
FROM (SELECT id FROM exams WHERE title = '2026년 1회 정보처리기사 실기 (AI 커스텀)' AND del_yn = 'N') e,
LATERAL (VALUES
(1, 'CODE',
 $q$다음 C 코드의 실행 결과를 쓰시오.$q$,
 $q$<p><br></p>$q$,
 $q$#include <stdio.h>

double maxVal(int p[], int len) {
    int mx = p[0];
    for (int i = 1; i < len; i++)
        if (p[i] > mx) mx = p[i];
    return (double) mx;
}

double minVal(int *p, int len) {
    int mn = *p;
    for (int i = 1; i < len; i++)
        if (*(p + i) < mn) mn = *(p + i);
    return (double) mn;
}

int main() {
    int arr[6] = {34, 78, 12, 90, 45, 67};
    printf("%.1f", (maxVal(arr, 6) + minVal(arr, 6)) / 2);
    return 0;
}$q$,
 'c', $q$51.0$q$,
 $q$최댓값 90(배열 인덱스 접근)과 최솟값 12(포인터 접근)의 평균 (90+12)/2 = 51.0.$q$),

(2, 'SHORT_ANSWER',
 $q$다음 설명에 해당하는 디자인 패턴의 유형을 괄호 안에 쓰시오.$q$,
 $q$<p>( ㄱ ) 패턴은 호환되지 않는 인터페이스를 가진 클래스들이 함께 동작하도록, 한 클래스의 인터페이스를 클라이언트가 기대하는 다른 인터페이스로 변환한다.</p><p>( ㄴ ) 패턴은 여러 알고리즘을 각각 캡슐화하여 서로 교환 가능하게 만들고, 클라이언트와 독립적으로 알고리즘을 선택·변경할 수 있게 한다.</p>$q$,
 NULL, NULL,
 $q$ㄱ. Adapter / ㄴ. Strategy$q$,
 $q$인터페이스 변환은 Adapter, 알고리즘군 캡슐화·교환은 Strategy.$q$),

(3, 'SHORT_ANSWER',
 $q$데이터베이스 설계 절차이다. 각 단계 설명에 해당하는 용어를 순서대로 쓰시오.$q$,
 $q$<p>( ㄱ ): 사용자 요구사항을 수집·분석하여 명세를 작성하는 단계</p><p>( ㄴ ): E-R 모델 등으로 DBMS에 독립적인 개념 스키마를 설계하는 단계</p><p>( ㄷ ): 목표 DBMS에 맞는 관계 스키마(테이블)로 변환하는 단계</p><p>( ㄹ ): 저장 구조·접근 경로·인덱스 등 물리적 저장을 설계하는 단계</p><p>( ㅁ ): DDL로 실제 데이터베이스를 생성하는 단계</p>$q$,
 NULL, NULL,
 $q$ㄱ. 요구사항 분석 / ㄴ. 개념적 설계 / ㄷ. 논리적 설계 / ㄹ. 물리적 설계 / ㅁ. 구현$q$,
 $q$요구사항 분석 → 개념적 설계 → 논리적 설계 → 물리적 설계 → 구현 순.$q$),

(4, 'SHORT_ANSWER',
 $q$다음 각 설명이 의미하는 비기능적 요구사항 유형을 보기에서 골라 쓰시오.$q$,
 $q$<p>1. 시스템이 장시간 중단 없이 지속적으로 서비스를 제공할 수 있어야 한다.</p><p>2. 동일 소프트웨어를 다른 운영체제·하드웨어 환경으로 옮겨서도 동작할 수 있어야 한다.</p><p>3. 인가되지 않은 접근·변조로부터 데이터를 보호해야 한다.</p><p>&lt;보기&gt; 신뢰성, 가용성, 성능, 이식성, 보안, 사용성, 유지보수성</p>$q$,
 NULL, NULL,
 $q$가용성, 이식성, 보안$q$,
 $q$지속 운영=가용성, 환경 이전=이식성, 접근 보호=보안.$q$),

(5, 'SHORT_ANSWER',
 $q$다음 설명에 해당하는 용어의 영문 약자를 쓰시오.$q$,
 $q$<p>다양한 보안 장비·시스템의 로그와 이벤트를 한곳에 수집·상관분석하여 실시간으로 위협을 탐지·대응하는 통합 보안 관제 시스템</p>$q$,
 NULL, NULL,
 $q$SIEM$q$,
 $q$Security Information and Event Management.$q$),

(6, 'SHORT_ANSWER',
 $q$HDLC 프로토콜에 대한 다음 설명에 알맞은 용어를 쓰시오.$q$,
 $q$<p>1. 실제 사용자 데이터를 담아 전송하는 프레임</p><p>2. 흐름 제어·오류 제어 등 링크 관리를 위한 제어 정보를 전달하는 프레임</p><p>3. 순서 번호 없이 링크 초기화·해제·모드 설정 등에 사용되는 프레임</p><p>4. 두 국(Station)이 대등한 위치에서 서로 명령과 응답을 주고받는 모드</p><p>5. 종국이 주국의 허가 없이도 자발적으로 응답을 전송할 수 있는 모드</p>$q$,
 NULL, NULL,
 $q$1. 정보(I) / 2. 감독(S) / 3. 비번호(U) / 4. 비동기 균형 모드(ABM) / 5. 비동기 응답 모드(ARM)$q$,
 $q$정보(I)·감독(S)·비번호(U) 프레임과 비동기 균형 모드(ABM)·비동기 응답 모드(ARM).$q$),

(7, 'CODE',
 $q$다음 Java 코드의 실행 결과를 쓰시오.$q$,
 $q$<p><br></p>$q$,
 $q$class Animal {
    String sound(Object o) { return "generic"; }
    String describe() { return sound("food"); }
}

class Dog extends Animal {
    String sound(Object o) { return "bark"; }
    String sound(String s) { return "woof"; }
}

public class Main {
    public static void main(String[] args) {
        Animal a = new Dog();
        System.out.println(a.describe());
    }
}$q$,
 'java', $q$bark$q$,
 $q$describe()는 정적 타입 Animal 기준으로 sound(Object)를 호출하고, 동적 디스패치로 Dog.sound(Object)가 실행되어 "bark". sound(String)은 오버로딩이라 선택되지 않는다.$q$),

(8, 'CODE',
 $q$다음 Python 코드에서 입력값이 python일 때의 실행 결과를 쓰시오.$q$,
 $q$<p><br></p>$q$,
 $q$s = input()
r = ''
for idx, ch in enumerate(s):
    if idx % 2 == 0:
        r += ch.upper()
    else:
        r += ch.lower()
print(r[::-1])$q$,
 'python', $q$nOhTyP$q$,
 $q$짝수 인덱스는 대문자, 홀수 인덱스는 소문자로 만들면 "PyThOn", 이를 뒤집으면 "nOhTyP".$q$),

(9, 'SHORT_ANSWER',
 $q$다음 각 SQL 구문의 실행 결과로 조회되는 행의 수를 쓰시오.$q$,
 $q$<p>ORDERS 테이블에는 고객 C1이 3건, C2가 5건, C3가 2건의 주문을 저장하고 있다.</p><p>1. SELECT COUNT(*) FROM ORDERS;</p><p>2. SELECT COUNT(DISTINCT CUST_ID) FROM ORDERS;</p><p>3. SELECT CUST_ID FROM ORDERS GROUP BY CUST_ID HAVING COUNT(*) >= 3;</p>$q$,
 NULL, NULL,
 $q$1. 10 / 2. 3 / 3. 2$q$,
 $q$전체 10행 / 고객 3종 / 3건 이상 주문 그룹은 C1(3)·C2(5) 2개.$q$),

(10, 'SHORT_ANSWER',
 $q$기존 테이블에 외래키 제약을 추가하려 한다. 다음 조건에 맞게 괄호 ①~③에 들어갈 예약어를 쓰시오.$q$,
 $q$<p>조건: 외래키 제약 조건 이름은 EMP_DEPT_FK, EMPLOYEE 테이블의 DEPT_NO 칼럼이 DEPARTMENT 테이블의 DNO 칼럼을 참조하도록 한다.</p><p>ALTER TABLE EMPLOYEE ADD ( ① ) EMP_DEPT_FK ( ② ) (DEPT_NO) ( ③ ) DEPARTMENT(DNO);</p>$q$,
 NULL, NULL,
 $q$① CONSTRAINT / ② FOREIGN KEY / ③ REFERENCES$q$,
 $q$ADD CONSTRAINT 제약명 FOREIGN KEY(칼럼) REFERENCES 참조테이블(참조칼럼).$q$),

(11, 'SHORT_ANSWER',
 $q$다음 조건을 참고하여 호스트 a, b의 네트워크 주소를 CIDR 표기법으로 쓰시오.$q$,
 $q$<p>호스트 a의 IP 주소: 172.16.10.100</p><p>호스트 b의 IP 주소: 172.16.20.5</p><p>서브넷 마스크: 255.255.252.0</p>$q$,
 NULL, NULL,
 $q$a. 172.16.8.0/22 / b. 172.16.20.0/22$q$,
 $q$255.255.252.0은 /22, 셋째 옥텟 블록 크기 4. 10→8, 20→20.$q$),

(12, 'CODE',
 $q$다음 C 코드의 실행 결과를 쓰시오.$q$,
 $q$<p><br></p>$q$,
 $q$#include <stdio.h>

int add10(int x) { return x + 10; }
int mul2(int x) { return x * 2; }

struct calc {
    int (*op)(int);
};

int main() {
    struct calc c[2];
    c[0].op = add10;
    c[1].op = mul2;
    int v = 5;
    printf("%d", c[0].op(v) + c[1].op(v));
    return 0;
}$q$,
 'c', $q$25$q$,
 $q$구조체 배열의 함수 포인터로 add10(5)=15, mul2(5)=10을 호출해 합 25.$q$),

(13, 'CODE',
 $q$다음 Python 코드의 실행 결과를 쓰시오.$q$,
 $q$<p><br></p>$q$,
 $q$data = list(range(2, 20, 3))
print('-'.join(str(x) for x in data[::-1]))$q$,
 'python', $q$17-14-11-8-5-2$q$,
 $q$range(2,20,3)=[2,5,8,11,14,17]을 뒤집어 '-'로 연결하면 17-14-11-8-5-2.$q$),

(14, 'CODE',
 $q$다음 Python 코드의 실행 결과를 쓰시오.$q$,
 $q$<p><br></p>$q$,
 $q$a = [[0] * 3] * 3
a[0][1] = 5
print(sum(row[1] for row in a))$q$,
 'python', $q$15$q$,
 $q$[[0]*3]*3은 같은 리스트 3개를 참조하므로 a[0][1]=5가 모든 행에 반영되어 5+5+5=15.$q$),

(15, 'SHORT_ANSWER',
 $q$다음 설명에 해당하는 공격 기법을 보기에서 고르시오.$q$,
 $q$<p>공격자는 실제 파일을 가리키는 링크 파일을 미리 만들어 두고, 프로그램이 임시 파일을 생성·확인하는 짧은 시점을 노려 그 링크로 바꿔치기한다. 프로그램은 링크가 가리키는 원본 파일을 정상 파일로 오인하여 접근하게 된다.</p><p>&lt;보기&gt; 하드링크 / 심볼릭링크 / 정적링크 / 동적링크</p>$q$,
 NULL, NULL,
 $q$심볼릭링크 || 심볼릭 링크 || Symbolic Link$q$,
 $q$링크 바꿔치기와 경쟁 조건을 이용하는 심볼릭 링크 공격.$q$),

(16, 'SHORT_ANSWER',
 $q$다음 설명에 해당하는 보안 공격 기법의 이름을 쓰시오.$q$,
 $q$<p>공격자는 표적이 자주 방문하는 합법적인 웹사이트를 미리 파악해 악성코드를 심어 두고, 표적이 접속하는 순간 악성코드가 실행되도록 유도한다. 불특정 다수가 아니라 특정 조직·인물을 노리며, 접속자의 환경을 확인해 표적에게만 선택적으로 감염시키기도 한다.</p>$q$,
 NULL, NULL,
 $q$워터링 홀 || 워터링홀 || Watering Hole$q$,
 $q$표적이 자주 찾는 사이트를 미끼로 삼는 워터링 홀 공격.$q$),

(17, 'CODE',
 $q$다음 Java 코드의 실행 결과를 쓰시오.$q$,
 $q$<p><br></p>$q$,
 $q$public class Main {
    public static void main(String[] args) {
        int a = 5;
        int b = 4;
        System.out.println("결과: " + a + b + (a + b));
    }
}$q$,
 'java', $q$결과: 549$q$,
 $q$문자열이 앞에 오면 이후는 모두 연결된다: "결과: "+5→"결과: 5", +4→"결과: 54", +(5+4=9)→"결과: 549". 괄호는 먼저 계산된다.$q$),

(18, 'SHORT_ANSWER',
 $q$다음 설명과 SQL 구문을 참고하여 실행 결과로 조회되는 값을 쓰시오.$q$,
 $q$<p>product 테이블의 상품별 가격(price): P1=100, P2=250, P3=400, P4=150</p><p>sales 테이블의 상품별 판매 건수(행 수): P1 4건, P2 2건, P3 1건, P4 3건</p><p>SELECT COUNT(*) FROM sales s JOIN product p ON s.pid = p.pid WHERE p.price &lt; (SELECT AVG(price) FROM product);</p>$q$,
 NULL, NULL,
 $q$7$q$,
 $q$평균 가격은 225. 미만 상품은 P1(100)·P4(150)이고 판매 건수 4+3=7행.$q$),

(19, 'SHORT_ANSWER',
 $q$통합 테스트에서 사용되는 더미 모듈에 대한 설명이다. 괄호 안에 알맞은 용어를 쓰시오.$q$,
 $q$<p>( 1 )은/는 아직 개발되지 않은 하위 모듈을 대신하여, 호출되면 미리 정한 값만 반환하는 가짜 모듈로 하향식 통합 테스트에 사용된다.</p><p>( 2 )은/는 아직 개발되지 않은 상위 모듈을 대신하여, 하위 모듈을 호출하고 그 결과를 확인하는 가짜 모듈로 상향식 통합 테스트에 사용된다.</p>$q$,
 NULL, NULL,
 $q$1. 스텁(Stub) / 2. 드라이버(Driver)$q$,
 $q$하향식=스텁, 상향식=드라이버.$q$),

(20, 'SHORT_ANSWER',
 $q$응집도의 유형에 대한 설명이다. 괄호 안에 들어갈 알맞은 용어를 쓰시오.$q$,
 $q$<p>( 1 )적 응집도는 모듈 내 모든 구성요소가 하나의 공통 목적을 위해 수행되는, 가장 바람직한 응집도이다.</p><p>( 2 )적 응집도는 초기화·종료처럼 특정 시점에 함께 실행되는 기능들이 한 모듈에 모인 경우의 응집도이다.</p><p>( 3 )적 응집도는 유사한 성격의 기능들을 묶고 제어 플래그로 실행할 기능을 선택하는 경우의 응집도이다.</p>$q$,
 NULL, NULL,
 $q$1. 기능 / 2. 시간 / 3. 논리$q$,
 $q$공통 목적=기능, 특정 시점=시간, 플래그 선택=논리.$q$)
) AS v(seq, qt, instr, content, code, lang, answer, expl)
WHERE NOT EXISTS (SELECT 1 FROM questions q WHERE q.exam_id = e.id);

-- 응시 대상 등록: examinations(사용자 시험 목록/응시)는 exam_paper_id로 위 exams(시험지)를 참조한다.
-- 기존 기출 시험과 동일하게 time_limit 150분, category_id 7(정보처리기사 실기)로 등록한다.
INSERT INTO examinations (created_at, time_limit, title, category_id, created_by, exam_paper_id)
SELECT now(), 150, '2026년 1회 정보처리기사 실기 (AI 커스텀)', 7, 1,
       (SELECT id FROM exams WHERE title = '2026년 1회 정보처리기사 실기 (AI 커스텀)' AND del_yn = 'N')
WHERE NOT EXISTS (
    SELECT 1 FROM examinations WHERE title = '2026년 1회 정보처리기사 실기 (AI 커스텀)'
);

COMMIT;

-- 검증
SELECT id, title, order_no FROM exams WHERE title = '2026년 1회 정보처리기사 실기 (AI 커스텀)';
SELECT seq, question_type, left(answer, 40) answer FROM questions
WHERE exam_id = (SELECT id FROM exams WHERE title = '2026년 1회 정보처리기사 실기 (AI 커스텀)' AND del_yn='N')
ORDER BY seq;
