-- 목적: 관리자 작성 패치노트와 사용자 공개 목록을 위한 patch_notes 테이블 생성
-- 적용 대상: PostgreSQL 15 / 신규 테이블 patch_notes
-- 정책: 게시 일시(published_dt)는 최초 게시 시 한 번만 기록하고, 삭제는 del_yn 논리 삭제를 사용한다.
-- 롤백: 파일 하단의 ROLLBACK 절차를 별도 실행한다.

BEGIN;

CREATE TABLE IF NOT EXISTS patch_notes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(200) NOT NULL,
    version       VARCHAR(50) NOT NULL,
    content       TEXT NOT NULL,
    published_yn  VARCHAR(1) NOT NULL DEFAULT 'N',
    published_dt  TIMESTAMP NULL,
    create_dt     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_uno    BIGINT NOT NULL,
    modified_dt   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_uno  BIGINT NOT NULL,
    del_yn        VARCHAR(1) NOT NULL DEFAULT 'N',
    use_yn        VARCHAR(1) NOT NULL DEFAULT 'Y'
);

CREATE INDEX IF NOT EXISTS idx_patch_notes_admin_list
    ON patch_notes (del_yn, modified_dt DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_patch_notes_public_list
    ON patch_notes (del_yn, use_yn, published_yn, published_dt DESC, id DESC);

COMMENT ON TABLE patch_notes IS '관리자 작성 패치노트';
COMMENT ON COLUMN patch_notes.published_yn IS '게시 여부 (Y/N)';
COMMENT ON COLUMN patch_notes.published_dt IS '최초 게시 일시';

COMMIT;

-- ROLLBACK (필요 시 아래 문장을 별도 트랜잭션으로 실행)
-- BEGIN;
-- DROP TABLE IF EXISTS patch_notes;
-- COMMIT;
