'use client';

import { useRef, useState } from 'react';
import { inquiryService, type UploadImageResult } from '@/services/inquiryService';

export function InquiryMessageComposer({ inquiryId, onSent, admin = false }: { inquiryId: number; onSent: () => void; admin?: boolean }) {
  const inputRef = useRef<HTMLInputElement>(null); const [content, setContent] = useState(''); const [images, setImages] = useState<UploadImageResult[]>([]); const [sendEmail, setSendEmail] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const upload = async (file?: File) => { if (!file || images.length === 3) return; setError(''); try { const response = await inquiryService.uploadMessageImage(file); if (response.data.data) setImages((current) => [...current, response.data.data!]); } catch { setError('이미지 업로드에 실패했습니다.'); } finally { if (inputRef.current) inputRef.current.value = ''; } };
  const submit = async () => { if (!content.trim() || busy) return; setBusy(true); setError(''); try { await (admin ? inquiryService.adminAddMessage(inquiryId, content.trim(), images.map((image) => image.id), sendEmail) : inquiryService.addMessage(inquiryId, content.trim(), images.map((image) => image.id))); setContent(''); setImages([]); setSendEmail(false); onSent(); } catch { setError('메시지 등록에 실패했습니다. 다시 시도해 주세요.'); } finally { setBusy(false); } };
  return <section className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 p-4 space-y-3"><textarea value={content} onChange={(event) => setContent(event.target.value)} rows={4} placeholder="추가 내용을 입력해 주세요." className="w-full rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-3 text-sm text-gray-800 dark:text-gray-100" />
    <div className="flex flex-wrap items-center gap-2">{images.map((image) => <button key={image.id} type="button" onClick={() => setImages((current) => current.filter((item) => item.id !== image.id))} className="text-xs text-indigo-600">첨부 이미지 ×</button>)}<button type="button" onClick={() => inputRef.current?.click()} className="text-xs text-gray-500">이미지 첨부 ({images.length}/3)</button><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/gif,image/webp" className="hidden" onChange={(event) => void upload(event.target.files?.[0])} />{admin && <label className="ml-auto text-xs text-gray-600 dark:text-gray-300"><input type="checkbox" checked={sendEmail} onChange={(event) => setSendEmail(event.target.checked)} className="mr-1" />사용자에게 이메일 알림 발송</label>}<button type="button" onClick={() => void submit()} disabled={busy || !content.trim()} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white disabled:opacity-50">{busy ? '등록 중...' : '메시지 등록'}</button></div>{error && <p className="text-xs text-red-600">{error}</p>}</section>;
}
